// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Oxs0c1JO9koKkjAythNsGXW75nVnUAU',
    appId: '1:431868311908:web:c3f443845afacd34696271',
    messagingSenderId: '431868311908',
    projectId: 'riaugo',
    authDomain: 'riaugo.firebaseapp.com',
    storageBucket: 'riaugo.firebasestorage.app',
    measurementId: 'G-QXL4J53X4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GfblBKR3-5hvd27rJBHTz4TS_Ebhi6o',
    appId: '1:431868311908:android:3c55c70b6574e606696271',
    messagingSenderId: '431868311908',
    projectId: 'riaugo',
    storageBucket: 'riaugo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYyZPkZlgUanGSSQqxAZrdF9wbFbjgjdI',
    appId: '1:431868311908:ios:64e9b54395024a13696271',
    messagingSenderId: '431868311908',
    projectId: 'riaugo',
    storageBucket: 'riaugo.firebasestorage.app',
    iosBundleId: 'com.example.riauGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYyZPkZlgUanGSSQqxAZrdF9wbFbjgjdI',
    appId: '1:431868311908:ios:64e9b54395024a13696271',
    messagingSenderId: '431868311908',
    projectId: 'riaugo',
    storageBucket: 'riaugo.firebasestorage.app',
    iosBundleId: 'com.example.riauGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Oxs0c1JO9koKkjAythNsGXW75nVnUAU',
    appId: '1:431868311908:web:002fd3fea5a3e6db696271',
    messagingSenderId: '431868311908',
    projectId: 'riaugo',
    authDomain: 'riaugo.firebaseapp.com',
    storageBucket: 'riaugo.firebasestorage.app',
    measurementId: 'G-P1D6L3VE3F',
  );
}
